server:
  port: 5050

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_format: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/test_erp
    username: electr
    password: 1
